name: Update WakaTime Stats
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *' # 每天UTC时间00:30运行

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update README with WakaTime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: "waka"
          COMMIT_MESSAGE: "chore: update coding stats"
          START_DATE: "2026-01-01" # 或更早，例如 "2025-12-01"
          END_DATE: "2026-01-02" 
          SHOW_TITLE: true
          LANG_COUNT: 5
